In [1]:
import numpy as np
import tensorflow as tf


**Trainning Phase**

In [2]:
!pip install opendatasets -q
import opendatasets as od

In [3]:
od.download("https://www.kaggle.com/datasets/manishguptads/news-headlines")


Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username:

  bawantharathnayake


Your Kaggle Key:

  ········


Dataset URL: https://www.kaggle.com/datasets/manishguptads/news-headlines


100%|██████████████████████████████████████████████████████████████████████████████████████| 243k/243k [00:00<00:00, 319kB/s]

In [5]:
with open("./news-headlines/ArticlesMarch2018.csv", 'r', encoding='utf-8') as file:
    news = file.read()


In [6]:
news

'articleID,byline,documentType,headline,keywords,multimedia,newDesk,printPage,pubDate,sectionName,snippet,source,typeOfMaterial,webURL,articleWordCount\n5a974697410cf7000162e8a4,By BINYAMIN APPELBAUM,article,"Virtual Coins, Real Resources","[\'Bitcoin (Currency)\', \'Electric Light and Power\', \'United States Economy\', \'Labor and Jobs\', \'Productivity\']",1,Business,1,01-03-2018 00:17,Economy,America has a productivity problem. One explanation may be the growing use of real resources to make virtual products.,The New York Times,News,https://www.nytimes.com/2018/02/28/business/economy/bitcoin-electricity-productivity.html,1207\n5a974be7410cf7000162e8af,By HELENE COOPER and ERIC SCHMITT,article,U.S. Advances Military Plans for North Korea,"[\'United States Defense and Military Forces\', \'North Korea\', \'United States International Relations\', \'United States Politics and Government\', \'Embargoes and Sanctions\', \'Civilian Casualties\', \'Defense Department\', \'Joint Chiefs of S

In [7]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()


In [8]:
tokenizer.fit_on_texts([news])

In [9]:
tokenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"articleid": 1, "byline": 1, "documenttype": 1, "headline": 1, "keywords": 1, "multimedia": 1, "newdesk": 1, "printpage": 1, "pubdate": 1, "sectionname": 1, "snippet": 1, "source": 3, "typeofmaterial": 1, "weburl": 1, "articlewordcount": 1, "5a974697410cf7000162e8a4": 1, "by": 1511, "binyamin": 1, "appelbaum": 1, "article": 1389, "virtual": 3, "coins": 1, "real": 47, "resources": 2, "\'bitcoin": 1, "currency": 1, "\'": 1579, "\'electric": 4, "light": 9, "and": 3101, "power\'": 6, "\'united": 480, "states": 470, "economy\'": 35, "\'labor": 24, "jobs\'": 24, "\'productivity\'": 5, "1": 1642, "business": 184, "01": 234, "03": 2861, "2018": 2896, "00": 507, "17": 121, "economy": 39, "america": 42, "has": 158, "a": 1355, "productivity": 2, "problem": 13, "one": 90, "explanation": 3, "may": 73, "be": 164, "the

In [10]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 '2018': 3,
 '03': 4,
 'new': 5,
 '1': 6,
 'york': 7,
 "'": 8,
 'by': 9,
 'times': 10,
 'com': 11,
 'article': 12,
 'https': 13,
 'www': 14,
 'nytimes': 15,
 'html': 16,
 'a': 17,
 'of': 18,
 'unknown': 19,
 'to': 20,
 'news': 21,
 'in': 22,
 '0': 23,
 'politics': 24,
 '00': 25,
 'for': 26,
 "'united": 27,
 'states': 28,
 'trump': 29,
 'us': 30,
 'is': 31,
 'on': 32,
 "government'": 33,
 'donald': 34,
 'with': 35,
 "j'": 36,
 "'trump": 37,
 '09': 38,
 'opinion': 39,
 'that': 40,
 'op': 41,
 'oped': 42,
 'ed': 43,
 '01': 44,
 '10': 45,
 '15': 46,
 '23': 47,
 '22': 48,
 'world': 49,
 'trade': 50,
 '12': 51,
 '14': 52,
 '20': 53,
 'an': 54,
 '16': 55,
 'it': 56,
 '19': 57,
 'at': 58,
 '13': 59,
 'business': 60,
 'as': 61,
 '02': 62,
 'are': 63,
 'what': 64,
 'from': 65,
 'review': 66,
 'be': 67,
 'but': 68,
 '21': 69,
 '28': 70,
 '18': 71,
 'has': 72,
 'you': 73,
 '27': 74,
 '08': 75,
 'learning': 76,
 '07': 77,
 'was': 78,
 'about': 79,
 '30': 80,
 'president': 81,


In [11]:
input_sequences = []
for sentence in news.split('\n'):
  #print(sentence)
  token_list = tokenizer.texts_to_sequences([sentence])[0]
  #print(token_list)
  for i in range(1, len(token_list)):
    sequence = token_list[:i+1]
    input_sequences.append(sequence)



In [12]:
input_sequences[ :5]

[[7082, 7083],
 [7082, 7083, 7084],
 [7082, 7083, 7084, 7085],
 [7082, 7083, 7084, 7085, 7086],
 [7082, 7083, 7084, 7085, 7086, 7087]]

In [13]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

153

In [14]:
# add padding
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))


In [15]:
input_sequences[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0, 70

In [16]:
# divide dataset into feature set (X) and labels (y)
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [17]:

X[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [18]:
y

array([ 7083,  7084,  7085, ...,  3288,    16, 15888])

In [19]:
# number of words
num_classes = len(tokenizer.word_index)+1
num_classes

15889

In [31]:
def sparse_one_hot_encoding(y, num_classes):
    indices = tf.expand_dims(tf.range(0, len(y), dtype=tf.int64), 1)
    y_sparse = tf.SparseTensor(indices, y, dense_shape=[len(y), num_classes])
    return tf.sparse.to_dense(tf.sparse.reorder(y_sparse))

# Example usage
y_encoded_sparse = sparse_one_hot_encoding(y, num_classes)

ValueError: Dimensions 1 and 2 are not compatible

In [25]:
# Example of batch processing
batch_size = 1024  # Adjust based on your system's memory capacity

for i in range(0, len(y), batch_size):
    batch_labels = y[i:i + batch_size]
    batch_encoded = tf.keras.utils.to_categorical(batch_labels, num_classes=num_classes)
    # Now use batch_encoded for training in this batch

In [21]:
# one-hot encoding labels
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))
     

MemoryError: Unable to allocate 13.1 GiB for an array with shape (110770, 15889) and data type float64

In [26]:
y[1]

7084

In [29]:
# model building
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [30]:

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:

# compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


In [ ]:
# model training
history = model.fit(X, y, epochs=100)

**Prediction Phase**


In [ ]:

input_text = "cricket begin"
for i in range(6):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)